export enum backendProject {
  LOGIN = 'LOGIN',
  FLOW_DEFINITION_SERVER = 'FLOW_DEFINITION_SERVER',
}
export enum CommonsResource {
  SESSION = 'SESSION',
  INITIAL_LOAD = 'INITIAL_LOAD',
  GRID_CONFIGURATION = 'GRID_CONFIGURATION',
  PERMISSION = 'PERMISSION',
  MODULE_ACCESS = 'MODULE_ACCESS',
  TRANSLATED_LISTS = 'TRANSLATED_LISTS',
  ALL_TRANSLATIONS = 'ALL_TRANSLATIONS',
  SEGMENTATION_CRITERIA_TRANSLATIONS = 'SEGMENTATION_CRITERIA_TRANSLATIONS',
  ADVANCE_SEARCH = 'ADVANCE_SEARCH',
  ADVANCE_SEARCH_FIELDS = 'ADVANCE_SEARCH_FIELDS',
  SEGMENTATION_CRITERIA = 'SEGMENTATION_CRITERIA',
  RIMM_TRANSLATIONS = 'RIMM_TRANSLATIONS',
  PASSWORD = 'PASSWORD',

  WILDCARD = 'WILDCARD',

  DATA_LOAD = 'DATA_LOAD',
  FLOW_GRAPH = 'FLOW_GRAPH',
}

export enum FilterOperator { //se esperan comparaciones por array menor que etc..
  LESS = 1,
  LESSOREQUAL = 2,
  EQUAL = 3,
  GREATEROREQUAL = 4,
  GREATER = 5,
  RANGE = 6,
}

export enum FilterType {
  TREESELECT = 'TREESELECT',
  RANGE = 'RANGE',
  TEXT = 'TEXT',
  SLIDERSELECTOR = 'SLIDERSELECTOR',
  DATE = 'DATE',
  NUMERIC = 'NUMERIC',
  SELECT = 'SELECT',
  PHONE = 'PHONE',
}

export enum ResourceMode {
  ENTITY = 'ENTITY',
  COLLECTION = 'COLLECTION',
  GRID = 'GRID',
  STATIC = 'STATIC',
}

export enum Permission {}

export enum ModulePermission {}
