export enum Conection {
  SERVER_ERROR = 'SERVER_ERROR',
  FAIL_TO_CONVERT_TO_JSON = 'FAIL_TO_CONVERT_TO_JSON',
  FAIL_TO_PARSE_FROM_JSON = 'FAIL_TO_PARSE_FROM_JSON',
  NO_SERVER_ACCESS = 'NO_SERVER_ACCESS',
  SERVER_INTERNAL_ERROR = 'SERVER_INTERNAL_ERROR',
  ERROR_EXPIRATION_TIME = 'ERROR_EXPIRATION_TIME',
  ERROR_VALIDATION_TOKEN = 'ERROR_VALIDATION_TOKEN',
}

export enum Resource {
  NOT_DEFINED_LOCATION = 'NOT_DEFINED_LOCATION',
  WRONG_RESOURCE_CONFIGURATION = 'WRONG_RESOURCE_CONFIGURATION',
}

export enum Code {
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  PARAM_MISSING = 'PARAM_MISSING',
  WRONG_PARAMETERS = 'WRONG_PARAMETERS',
  CODE_UNHANDLED = 'CODE_UNHANDLED',
  NOT_EXPECTED_VALUE = 'NOT_EXPECTED_VALUE',
}

export enum Form {
  NOT_VALID_NUMBER = 'NOT_VALID_NUMBER',
}
